'use client'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
type FeeItem = { vendorId:number; vendorName:string; settledRevenue:number; feeType:'fixed'|'percentage'; fixedFee:number; revenueFeePercent:number; totalFee:number; collectionStatus:'uncollected'|'collected' }
const money = (value:number) => `${value.toLocaleString('vi-VN')} ₫`
export default function VendorMonthlyFeesPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [items, setItems] = useState<FeeItem[]>([]); const [loading, setLoading] = useState(true); const [collecting, setCollecting] = useState<number | null>(null)
  const load = async () => { setLoading(true); const response = await fetch(`/api/admin/vendor-monthly-fees?month=${month}`); const data = await response.json(); setItems(response.ok ? data.items : []); setLoading(false) }
  useEffect(() => { void load() }, [month])
  const collect = async (item:FeeItem) => { setCollecting(item.vendorId); await fetch('/api/admin/vendor-monthly-fees', {method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({...item, billingMonth:`${month}-01`, status:'collected'})}); setCollecting(null); void load() }
  const total = items.reduce((sum, item) => sum + item.totalFee, 0)
  return <main className="p-6"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Phí hàng tháng của shop</h1><p className="mt-1 text-muted-foreground">Báo cáo nội bộ. Muốn chỉnh mức phí, hãy vào chi tiết của từng shop.</p></div><label className="text-sm font-medium">Kỳ tính phí<input type="month" className="mt-1 block rounded-md border border-input bg-background px-3 py-2" value={month} onChange={(event) => setMonth(event.target.value)} /></label></div><Card className="mb-6"><CardHeader><CardTitle>Tổng phí dự kiến: {money(total)}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Chỉ tính từ đơn đã hoàn tất trong kỳ; chưa tự động trừ tiền shop.</CardContent></Card><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-4 text-left">Shop</th><th className="p-4 text-right">Doanh thu hoàn tất</th><th className="p-4 text-right">Loại phí</th><th className="p-4 text-right">Mức phí</th><th className="p-4 text-right">Phí dự kiến</th><th className="p-4 text-center">Trạng thái</th><th className="p-4 text-center">Thu phí</th></tr></thead><tbody>{loading ? <tr><td className="p-6 text-center" colSpan={7}>Đang tải...</td></tr> : items.map((item) => <tr key={item.vendorId} className="border-b"><td className="p-4 font-medium">{item.vendorName}</td><td className="p-4 text-right">{money(item.settledRevenue)}</td><td className="p-4 text-right">{item.feeType === 'fixed' ? 'Phí cố định' : '% doanh thu'}</td><td className="p-4 text-right">{item.feeType === 'fixed' ? money(item.fixedFee) : `${item.revenueFeePercent}%`}</td><td className="p-4 text-right font-semibold">{money(item.totalFee)}</td><td className="p-4 text-center"><span className={item.collectionStatus === 'collected' ? 'text-emerald-600' : 'text-amber-600'}>{item.collectionStatus === 'collected' ? 'Đã thu' : 'Chưa thu'}</span></td><td className="p-4 text-center">{item.collectionStatus === 'collected' ? '—' : <Button size="sm" disabled={collecting === item.vendorId} onClick={() => void collect(item)}>{collecting === item.vendorId ? 'Đang xử lý...' : 'Thu phí'}</Button>}</td></tr>)}</tbody></table></div></CardContent></Card></main>
}
