'use client'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'

type FeeConfig = { feeType: 'fixed' | 'percentage'; fixedMonthlyFee: number; revenueFeePercent: number; effectiveFrom?: string }

export function AdminVendorFeeModal({ vendor, open, onClose, onSaved }: { vendor: { id: number; name: string } | null; open: boolean; onClose: () => void; onSaved?: (config: FeeConfig) => void }) {
  const [feeType, setFeeType] = useState<'fixed' | 'percentage'>('fixed'); const [fixedMonthlyFee, setFixedMonthlyFee] = useState(0); const [revenueFeePercent, setRevenueFeePercent] = useState(0); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!vendor || !open) return; void fetch(`/api/admin/vendor-monthly-fees?vendorId=${vendor.id}`).then((response) => response.json()).then((data) => { const config = data.config; setFeeType(config.feeType); setFixedMonthlyFee(Number(config.fixedMonthlyFee || 0)); setRevenueFeePercent(Number(config.revenueFeePercent || 0)) }) }, [vendor?.id, open])
  const save = async () => { if (!vendor) return; setSaving(true); try { const response = await fetch('/api/admin/vendor-monthly-fees', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ vendorId: vendor.id, feeType, fixedMonthlyFee, revenueFeePercent }) }); const result = await response.json(); if (response.ok) { onSaved?.(result.config); onClose() } } finally { setSaving(false) } }
  return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent><DialogHeader><DialogTitle>Cấu hình phí: {vendor?.name}</DialogTitle></DialogHeader><div className="space-y-4"><label className="block text-sm font-medium">Loại phí<select className="mt-1 block w-full rounded border p-2" value={feeType} onChange={(event) => setFeeType(event.target.value as 'fixed' | 'percentage')}><option value="fixed">Phí cố định hàng tháng</option><option value="percentage">Phần trăm doanh thu</option></select></label>{feeType === 'fixed' ? <label className="block text-sm font-medium">Phí cố định (₫)<input type="number" min="0" className="mt-1 block w-full rounded border p-2" value={fixedMonthlyFee} onChange={(event) => setFixedMonthlyFee(Number(event.target.value))} /></label> : <label className="block text-sm font-medium">Tỷ lệ doanh thu (%)<input type="number" min="0" max="100" step="0.01" className="mt-1 block w-full rounded border p-2" value={revenueFeePercent} onChange={(event) => setRevenueFeePercent(Number(event.target.value))} /></label>}</div><DialogFooter><Button variant="outline" onClick={onClose}>Hủy</Button><Button disabled={saving} onClick={() => void save()}>{saving ? 'Đang lưu...' : 'Lưu cấu hình'}</Button></DialogFooter></DialogContent></Dialog>
}
