'use client'
import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

const money = (value: number) => `${Number(value || 0).toLocaleString('vi-VN')} ₫`
const statusLabel = (status: string) => status === 'collected' ? 'Đã thanh toán' : status === 'partially_collected' ? 'Thanh toán một phần' : 'Chưa thanh toán'
export default function SellerMonthlyFeesPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [data, setData] = useState<any>(null); const [error, setError] = useState('')
  useEffect(() => { void fetch(`/api/seller/monthly-fees?month=${month}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); setError('') }).catch((reason) => setError(reason.message || 'Không thể tải phí hợp tác.')) }, [month])
  const current = data?.current
  return <main className="p-4 md:p-6"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Phí hợp tác hàng tháng</h1><p className="mt-1 text-sm text-muted-foreground">Theo dõi số tiền shop cần thanh toán cho sàn.</p></div><label className="text-sm font-medium">Kỳ phí<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="mt-1 block rounded-md border bg-background px-3 py-2" /></label></div>{error ? <p className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : <><div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Cần thanh toán kỳ này</CardTitle></CardHeader><CardContent className="text-xl font-bold">{money(current?.totalFee)}</CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Đã thanh toán</CardTitle></CardHeader><CardContent className="text-xl font-bold text-emerald-600">{money(current?.collectedAmount)}</CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Còn nợ kỳ này</CardTitle></CardHeader><CardContent className="text-xl font-bold text-amber-600">{money(current?.remainingAmount)}</CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Tổng dư nợ các kỳ</CardTitle></CardHeader><CardContent className="text-xl font-bold text-red-600">{money(data?.totalDebt)}</CardContent></Card></div><Card><CardHeader><CardTitle>Lịch sử phí hợp tác</CardTitle><p className="text-sm text-muted-foreground">Mức phí: {data?.config?.feeType === 'percentage' ? `${data?.config?.rate || 0}% doanh thu` : `${money(data?.config?.rate)} / tháng`}</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-sm"><thead className="border-y bg-muted/50"><tr><th className="p-3 text-left">Kỳ phí</th><th className="p-3 text-right">Cần thanh toán</th><th className="p-3 text-right">Đã thanh toán</th><th className="p-3 text-right">Còn nợ</th><th className="p-3 text-center">Trạng thái</th></tr></thead><tbody>{(data?.history || []).map((item: any) => <tr key={item.billingMonth} className="border-b"><td className="p-3 font-medium">{new Date(`${item.billingMonth}T00:00:00`).toLocaleDateString('vi-VN', { month: '2-digit', year: 'numeric' })}</td><td className="p-3 text-right">{money(item.totalFee)}</td><td className="p-3 text-right text-emerald-600">{money(item.collectedAmount)}</td><td className="p-3 text-right text-amber-600">{money(item.remainingAmount)}</td><td className="p-3 text-center">{statusLabel(item.status)}</td></tr>)}</tbody></table></div></CardContent></Card></>}</main>
}
